name: 🚀 自動外送網頁到免費主機

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 同步檔案
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 步驟1：取得最新程式碼
      uses: actions/checkout@v4

    - name: 📂 步驟2：透過 FTP 同步到 InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./htdocs/11501_FULL_PHP